language: ruby
sudo: required
services:
  - docker
cache:
  - bundler
rvm:
  - 2.3
env:
  global:
    - KITCHEN_YAML=.kitchen.docker.yml
  matrix:
    - CHEF_VERSION=11
    - CHEF_VERSION=12
install: travis_wait bundle install --jobs=3 --retry=3 --deployment --path=${BUNDLE_PATH:-vendor/bundle}
script: bundle exec kitchen test --concurrency=3 --destroy=always
matrix:
  fast_finish: true
  include:
    - sudo: false
      env: []
      rvm: 2.3
      script: bundle exec rake test
    - sudo: false
      env: []
      rvm: 1.9
      gemfile: gemfiles/chef-11/Gemfile
      script: bundle exec rspec spec
